---
title: "MLB Data Viz"
output: html_notebook
---

```{r}
library(baseballr)
library(mlbplotR)
library(dplyr)
library(teamcolors)
library(ggplot2)
library(tidyverse)
library(gghighlight)
```


```{r}
# Filters the teamcolors package to only include MLB teams
MLB_colors = teamcolors[teamcolors$league == "mlb",]

# Creates and adds the abbreviations of the MLB teams to the MLB_colors df
Team = c("ARI", "ATL", "BAL", "BOS", "CHC", "CHW", "CIN", "CLE", "COL", "DET", "HOU", "KCR", "LAA", "LAD", "MIA", "MIL", "MIN", "NYM", "NYY", "OAK", "PHI", "PIT", "SDP", "SFG", "SEA", "STL", "TBR", "TEX", "TOR", "WAS")
MLB_colors = cbind(MLB_colors, Team)
```


```{r}
# Fangraphs batter data
fg_batter <- fg_batter_leaders(2023, 2023) |> left_join(MLB_colors, by = c("Team" = "Team"))

# Fangraphs pitcher data
fg_pitcher <- fg_pitcher_leaders(2023, 2023) |> left_join(MLB_colors, by = c("Team" = "Team"))
```


FG Batter Graphs
```{r}
fg_batter |> ggplot(aes(x = `Contact_pct`, y = `Z-Swing_pct`)) +
  geom_point(aes(fill = primary, color = secondary, size = PA), shape = 21, alpha = 0.9) +
scale_color_identity(aesthetics = c("fill", "color")) +
#gghighlight(Name == "Vinnie Pasquantino") +
#gghighlight(Team == "MIN") +
ggrepel:: geom_label_repel(aes(label = Name)) + theme_bw() + geom_hline(yintercept = mean(fg_batter$`Z-Swing_pct`), linetype = "dashed") + geom_vline(xintercept = mean(fg_batter$Contact_pct), linetype = "dashed") + labs(x = "Contact%", y = "Z-Swing%", title = "Contact and Z Swing%, 2023", caption = "Data: FanGraphs | @Cam_Kaplinger") + scale_x_continuous(breaks = scales::pretty_breaks(n = 8)) + scale_y_continuous(breaks = scales::pretty_breaks(n = 8)) +
  theme(plot.title = element_text(size = 22, hjust = 0.5, face = "bold"), plot.subtitle = element_text(size = 16, hjust = 0.5))

#ggsave("Charts/Vinnie Pasquantino/Contact and Z Swing_pct, 5-14-2023.png", width = 14, height = 10, dpi = "retina")
```

FG Pitcher Graphs
```{r}
fg_pitcher|> ggplot(aes(x = BABIP, y = ERA-SIERA)) +
  geom_point(aes(fill = primary, color = secondary, size = Pitches), shape = 21, alpha = 0.9) + 
scale_color_identity(aesthetics = c("fill", "color")) +
#gghighlight(Name == "Dylan Cease") +
#gghighlight(Team == "MIN") +
ggrepel:: geom_label_repel(aes(label = Name)) + theme_bw() + geom_hline(yintercept = mean(fg_pitcher$ERA - fg_pitcher$SIERA), linetype = "dashed") + geom_vline(xintercept = mean(fg_pitcher$BABIP), linetype = "dashed") + labs(x = "BABIP", y = "ERA-SIERA", title = "BABIP and ERA-SIERA, 2023", caption = "Data: FanGraphs | @Cam_Kaplinger") + scale_x_continuous(breaks = scales::pretty_breaks(n = 8)) + scale_y_continuous(breaks = scales::pretty_breaks(n = 8)) +
  theme(plot.title = element_text(size = 22, hjust = 0.5, face = "bold"), plot.subtitle = element_text(size = 16, hjust = 0.5))

#ggsave("Charts/BABIP and ERA-SIERA, 5-14-2023.png", width = 14, height = 10, dpi = "retina")
```